name: dash_chat
description: The most complete Chat UI for flutter inspired by react-native-gifted-chat.
version: 1.2.0
homepage: https://github.com/LostInDarkMath/dash_chat

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_parsed_text: ^2.2.1
  uuid: ^3.0.6
  intl: ^0.17.0
  transparent_image: ^2.0.0

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
